SET(CMAKE_SYSTEM_NAME Windows)
if (NOT CMAKE_C_COMPILER)
    SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
endif()
if (NOT CMAKE_CXX_COMPILER)
    SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
endif()
if (NOT CMAKE_RC_COMPILER)
    SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
endif()
SET(BLAS_LIBRAIRES /usr/local/mingw64/x86_64-w64-mingw32/bin/libblas.dll)
SET(LAPACK_LIBRAIRES /usr/local/mingw64/x86_64-w64-mingw32/bin/liblapack.dll)
