version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
platform: x64
configuration: Release
clone_folder: c:\projects\pnl
build_script:
    - if exist "build" ( rmdir build /s /q )
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=%configuration% -G "Visual Studio 16 2019" .. || exit /b 1
    - cmake --build . --config %configuration% || exit /b 1
    - cp "src/%configuration%/pnl.dll" "examples/%configuration%"
test_script:
    - ctest --output-on-failure --build-config %configuration%
