#!/bin/bash

# This script is used to determine how to link an executable to PNL without using CMake
# directly. We use a link sequence generated by CMake and we split it into pieces.

INSTALL_PREFIX=$1
BUILD_DIR=$2
pnl_includedir=$INSTALL_PREFIX/include
pnl_libdir=$INSTALL_PREFIX/lib
LINK_TXT=$BUILD_DIR/examples/CMakeFiles/array_test.dir/link.txt
# Drop the compiler name, fix after
CMAKE_LINK_COMMAND1=$(cat ${LINK_TXT} | sed -e 's/^[^ ]* //' )
# Fix libpnl path with full path
CMAKE_LINK_COMMAND=$(echo ${CMAKE_LINK_COMMAND1} | sed "s![^ ]*\(libpnl[^ ]*\.[^ ]*\) !${INSTALL_PREFIX}/lib/\1 !")
# Get flags at the end of the command
CMAKE_LINK_COMMAND_FLAGS_AFTER=$(echo ${CMAKE_LINK_COMMAND} | sed 's/^.*\.c\.o -o array_test//' | sed "s!${BUILD_DIR}/src!${pnl_libdir}!g")
# Get flags at the beginning of the command
CMAKE_LINK_COMMAND_FLAGS_BEFORE=$(echo ${CMAKE_LINK_COMMAND} | sed  -e 's/\( [^ ]*\.c\.o\)*//g' -e 's/\(.*\)-o array_test.*/\1/' )

# Insert the flags into build-dir/CMakeuser.incl
sed -i~ "s!^CMAKE_LINK_COMMAND_FLAGS_BEFORE=.*\$!CMAKE_LINK_COMMAND_FLAGS_BEFORE=${CMAKE_LINK_COMMAND_FLAGS_BEFORE}!" ${BUILD_DIR}/CMakeuser.incl
sed -i~ "s!^CMAKE_LINK_COMMAND_FLAGS_AFTER=.*\$!CMAKE_LINK_COMMAND_FLAGS_AFTER=${CMAKE_LINK_COMMAND_FLAGS_AFTER}!" ${BUILD_DIR}/CMakeuser.incl