## list of extra linker flags
LDFLAGS=

## Flags to be passed to the compiler
CFLAGS=

## list of executables to create
BINS=pipo

pipo_OBJS=main.o

## This line must be the last one
include ../Makeuser.incl

