## list of extra linker flags
LDFLAGS=

## Flags to be passed to the compiler
CFLAGS=

## list of executables to create
BINS=pipo

## Compiling rule for pipo
pipo_SRC=main.cxx hello.c
pipo_LDFLAGS=
pipo_CFLAGS=-O2 
pipo_CXXFLAGS=-O2

## See the manual section 1.3.1 for more details on the 
## syntax of this Makefile.

## This line must be the last one
include ../build/CMakeuser.incl

