## list of extra linker flags
LDFLAGS=

## Flags to be passed to the compiler
CFLAGS=

## list of executables to create
BINS=pipo
pipo_SRC=main.cxx hello.c
pipo_LDFLAGS=
pipo_CFLAGS=-ansi -O2 -pedantic
pipo_CXXFLAGS=-O2 -pedantic

## This line must be the last one
include ../build/CMakeuser.incl

