
# terminer la compilation en creant le dll a la main 
# creation du dll 

all:  shared-win32 

ARCS=common/.libs/libcommon.a mod/.libs/libmod.a opt/.libs/libopt.a \
	 libpnl/src/libpnl.dll -lstdc++  -lm

shared-win32:: $(OBJS1) 
	gcc -mno-cygwin -shared -o libpremia.dll premia_obj.o \
		-Wl,--export-all-symbols -Wl,--allow-multiple-definition \
		-Wl,--enable-auto-import -Wl,--whole-archive $(ARCS)  \
		-Wl,--no-whole-archive -Xlinker --out-implib -Xlinker libpremia.dll.a 




 

